baseURL = "https://delphi.cmu.edu/"
languageCode = "en-us"
title = "DELPHI"
theme = "delphi"
googleAnalytics = "UA-88748454-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$", "\\.rda$"]
disqusShortname = ""
relativeURLs = false

[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"
[[menu.main]]
    identifier = "about"
    name = "About"
    pre = "solid/info-circle"
    url = "/about"
    weight = 1

# About
[[menu.main]]
    parent = "about"
    name = "Delphi Research Group"
    url = "/about"
    weight = 1
[[menu.main]]
    parent = "about"
    name = "Team"
    url = "/about/team"
    weight = 2
[[menu.main]]
    parent = "about"
    name = "Center of Excellence"
    url = "/about/center-of-excellence"
    weight = 3
[[menu.main]]
    parent = "about"
    name = "Publications"
    url = "/about/publications"
    weight = 4
[[menu.main]]
    parent = "about"
    name = "Blog"
    url = "/blog"
    weight = 5
[[menu.main]]
    parent = "about"
    name = "News"
    url = "/about/news"
    weight = 6
[[menu.main]]
    parent = "about"
    name = "GitHub"
    url = "https://github.com/cmu-delphi/"
    weight = 7

# covid19
[[menu.main]]
    identifier = "covid19"
    name = "COVID-19"
    pre = "solid/virus"
    url = "/covid19/"
    weight = 2
[[menu.main]]
    parent = "covid19"
    name = "Delphi's COVID-19 Response Team"
    url = "/covid19/"
    weight = 1
[[menu.main]]
    parent = "covid19"
    name = "Surveys"
    url = "/covidcast/surveys"
    weight = 10
[[menu.main]]
    parent = "covid19"
    name = "Survey Results"
    url = "/covidcast/survey-results"
    weight = 11
[[menu.main]]
    identifier = "covid19-covidcast"
    parent = "covid19"
    name = "COVIDcast"
    url = "/covidcast/"
    weight = 20
[[menu.main]]
    parent = "covid19"
    name = "Export Data"
    url = "/covidcast/export"
    weight = 30
[[menu.main]]
    parent = "covid19"
    name = "Terms Of Use"
    url = "/covidcast/terms-of-use"
    weight = 40

# flu
[[menu.main]]
    identifier = "flu"
    name = "Flu"
    pre = "solid/disease"
    url = "/flu/"
    weight = 3
[[menu.main]]
    parent = "flu"
    name = "Delphi's Influenca Task Group"
    url = "/flu/"
    weight = 1
[[menu.main]]
    identifier = "flu-nowcast"
    parent = "flu"
    name = "Nowcast"
    url = "/nowcast/"
    weight = 10
[[menu.main]]
    identifier = "flu-crowdcast"
    parent = "flu"
    name = "Crowdcast"
    url = "/crowdcast/"
    weight = 20
[[menu.main]]
    identifier = "flu-fluscores"
    parent = "flu"
    name = "FluScores"
    url = "/misc/fluscores/"
    weight = 30

# forecasting
[[menu.main]]
    identifier = "forecasting"
    name = "Forecasting"
    pre = "solid/binoculars"
    url = "/forecasting/"
    weight = 4
[[menu.main]]
    parent = "forecasting"
    name = "Epidemiologic Forecasting"
    url = "/forecasting/"
    weight = 1
[[menu.main]]
    identifier = "forecasting-eval"
    parent = "forecasting"
    name = "Forecast Evaluation"
    url = "/forecast-eval/"
    weight = 10

# tools
[[menu.main]]
    identifier = "tools"
    name = "Tools"
    pre = "solid/tools"
    url = "/tools/"
    weight = 5
[[menu.main]]
    parent = "tools"
    name = "Delphi Tools"
    url = "/tools/"
    weight = 1
[[menu.main]]
    parent = "tools"
    name = "EpiVis"
    url = "/epivis/"
    weight = 10
[[menu.main]]
    parent = "tools"
    name = "COVIDcast"
    url = "/covidcast/"
    weight = 20
[[menu.main]]
    parent = "tools"
    name = "Indicator Status Overview"
    url = "/covidcast/indicator-status"
    weight = 30
[[menu.main]]
    parent = "tools"
    name = "Dashboard Builder"
    url = "/covidcast/dashboard"
    weight = 40
[[menu.main]]
    parent = "tools"
    name = "Forecast Evaluation"
    url = "/forecast-eval/"
    weight = 50
[[menu.main]]
    parent = "tools"
    name = "Nowcast"
    url = "/nowcast/"
    weight = 60
[[menu.main]]
    parent = "tools"
    name = "Crowdcast"
    url = "/crowdcast/"
    weight = 70
[[menu.main]]
    parent = "tools"
    name = "FluScores"
    url = "/misc/fluscores/"
    weight = 80

[[menu.main]]
    identifier = "api"
    name = "API"
    pre = "solid/database"
    url = "https://cmu-delphi.github.io/delphi-epidata/"
    weight = 100

[params]
    description = "Developing the Theory and Practice of Epidemiological Forecasting"
    mission = "Develop the theory and practice of epidemiological forecasting, with a long-term vision of making this technology as universally accepted and useful as weather forecasting is today."
    apiUrl = "https://cmu-delphi.github.io/delphi-epidata"
    twitter = "CmuDelphi"
    contactForm = "https://docs.google.com/forms/d/e/1FAIpQLScqgT1fKZr5VWBfsaSp-DNaN03aV6EoZU4YljIzHJ1Wl_zmtg/viewform"
    feedbackForm = "https://docs.google.com/forms/d/e/1FAIpQLSeIeOJtrAhdOriEyiRY7LkpQX8DZBY19dl6De8l56Q9CZhmxw/viewform?usp=pp_url&entry.1245962748="
    feedbackLikelihoodMobile = 0.2
    feedbackLikelihoodDesktop = 1
    feedbackDelayMin = 45  # in sec
    feedbackDelayMax = 180 # in sec
    feedbackDuration = 60  # show it for 60sec
    highlightLinks = "/covidcast/correlation,/covidcast/data-anomalies"
