baseURL = "https://delphi.cmu.edu/"
languageCode = "en-us"
title = "The Delphi Team"
theme = "delphi"
googleAnalytics = "UA-88748454-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
disqusShortname = ""
relativeURLs = false

[permalinks]
    post = "/:year/:month/:day/:slug/"
[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 1
[[menu.main]]
    parent = "about"
    name = "Team"
    url = "/about/team"
    weight = 1
[[menu.main]]
    identifier = "covidcast"
    name = "COVIDcast"
    pre = "map"
    url = "/covidcast"
    weight = 2
[[menu.main]]
    parent = "covidcast"
    name = "Surveys"
    url = "/covidcast/surveys"
    weight = 1
[[menu.main]]
    parent = "covidcast"
    name = "Methods"
    url = "/covidcast/methodology"
    weight = 2
[[menu.main]]
    parent = "covidcast"
    name = "Terms Of Use"
    url = "/covidcast/terms-of-use"
    weight = 3
[[menu.main]]
    identifier = "blog"
    name = "Blog"
    pre = "blog"
    url = "/blog"
    weight = 3
[[menu.main]]
    identifier = "github"
    name = "GitHub"
    pre = "github"
    url = "https://github.com/cmu-delphi/"
    weight = 4
[[menu.main]]
    identifier = "api"
    name = "API"
    pre = "api"
    url = "https://cmu-delphi.github.io/delphi-epidata/"
    weight = 5

[params]
    description = "Developing the Theory and Practice of Epidemiological Forecasting"
    showReadMore = true
    apiUrl = "https://cmu-delphi.github.io/delphi-epidata/api"

    [params.logo]
    url = "delphi_logo.png"
    width = 50
    height = 50
    alt = "Logo"
