baseURL = "https://delphi.cmu.edu/"
languageCode = "en-us"
title = "The Delphi Team"
theme = "delphi"
googleAnalytics = "UA-88748454-1"
disqusShortname = ""
relativeURLs = false

[permalinks]
    post = "/:year/:month/:day/:slug/"
[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    post = "angle-down"
    weight = 1
[[menu.main]]
    identifier = "team"
    parent = "about"
    name = "Team"
    url = "/about/team"
    weight = 1
[[menu.main]]
    name = "COVIDcast"
    pre = "map"
    url = "/covidcast"
    weight = 2
[[menu.main]]
    name = "Blog"
    pre = "blog"
    url = "/blog"
    weight = 3
[[menu.main]]
    name = "GitHub"
    pre = "github"
    url = "https://github.com/cmu-delphi/"
    weight = 4
[[menu.main]]
    name = "API"
    pre = "api"
    url = "https://cmu-delphi.github.io/delphi-epidata/"
    weight = 5

[params]
    description = "Developing the Theory and Practice of Epidemiological Forecasting"
    highlight = true
    math = true
    showReadMore = true

    [params.logo]
    url = "delphi_logo.png"
    width = 50
    height = 50
    alt = "Logo"
