baseURL = "https://delphi.cmu.edu/"
languageCode = "en-us"
title = "The Delphi Team"
theme = "delphi"
googleAnalytics = "UA-88748454-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$", "\\.rda$"]
disqusShortname = ""
relativeURLs = false

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    identifier = "main"
    name = "Delphi"
    url = "/"
    weight = 1
[[menu.main]]
    name = "COVIDcast"
    url = "/covidcast"
    weight = 2
[[menu.main]]
    name = "Data"
    url = "https://cmu-delphi.github.io/delphi-epidata/"
    weight = 3
[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 4
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/cmu-delphi/"
    weight = 5

[params]
    description = "Developing the Theory and Practice of Epidemiological Forecasting"
    showReadMore = true

    [params.logo]
    url = "delphi_logo.png"
    width = 50
    height = 50
    alt = "Logo"
