name: www-main
channels:
  - defaults
  - conda-forge
dependencies:
  - gdal=3.0.2
  - python=3.7.9  
  - pip=20.2.4
  - r-base=3.6.1
  - r-devtools=2.0.2
  - r-gridextra=2.3
  - r-reticulate=1.12
  - pandoc
  - fiona
  - geopandas
  - pandas
  - numpy
  - pillow
  - pyproj
  - matplotlib
  - pip:
    - covidcast==0.1.0