[build]
publish = "public"
command = "hugo --config config.toml,netlify.config.toml --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.78.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"