[build]
publish = "public"
command = "npm ci && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.production.environment]
HUGO_VERSION = "0.87.0"
HUGO_ENV = "production"
NODE_VERSION = "14.16.0"
NPM_VERSION = "6.14.11"

[context.deploy-preview]
command = "npm ci && hugo --gc --minify --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.87.0"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "14.16.0"
NPM_VERSION = "6.14.11"

[context.branch-deploy]
command = "npm ci && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.87.0"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "14.16.0"
NPM_VERSION = "6.14.11"
