name: blog

on:
  push:
    paths: # run only when an Rmd file changes
      - "**.Rmd"
      - "environment.yml"
      - "dependencies.R"
      - ".github/workflows/blog.yaml"
  workflow_dispatch:

jobs:
  blog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      RETICULATE_PYTHON: /usr/share/miniconda3/envs/www-main/bin/python
    steps:
      - uses: actions/checkout@v3
        with:
          # submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 3
      - uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-file: environment.yml
          micromamba-version: latest
      - name: Get Date
        id: get-date
        run: echo "name=today::$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Create environment
        run: micromamba env create -n www-main-micromamba -f environment.yml
      - name: Conda info
        run: |
          conda info
          conda list
      - name: Install R dependencies
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript ./dependencies.R
      - name: Restore Blogdown Cache
        uses: actions/cache@v3.0.2
        with:
          path: |
            ./blogdown
          key: ${{ runner.os }}-blogdown2-${{ hashFiles('environment.yml') }}-${{ hashFiles('content/blog/**.Rmd') }}
          restore-keys: |
            ${{ runner.os }}-blogdown2-${{ hashFiles('environment.yml') }}-
            ${{ runner.os }}-blogdown2-
      - name: Build site
        run: |
          npm run build:blog
      - uses: actions/upload-artifact@v3
        with:
          name: blog
          path: |
            ./content/blog
            ./static/blog

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3.0.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: website
          path: ./public
