on:
  push

name: ci

# based on https://github.com/r-lib/actions/blob/master/examples/blogdown.yaml

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Conda setup
        uses: s-weigand/setup-conda@v1.0.3
        with:
          update-conda: true
          python-version: 3.7      
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ~/anaconda3/pkgs
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-
      - name: Conda environment creation
        run: |
          conda env create -f environment.yml
      - name: Install R dependencies
        run: |
          source activate www-main
          Rscript ./dependencies.R
      - name: Build site
        run: |
          source activate www-main
          Rscript -e 'blogdown::build_site(run_hugo=FALSE)'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.0'
          extended: true

      - name: Build
        run: hugo --minify

      - uses: actions/upload-artifact@v2
        with:
          name: website
          path: ./public

      - name: Deploy Main
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public

