name: Dependabot auto-assign reviewer
on: pull_request

permissions: write-all

jobs:
  dependabot:
    runs-on: ubuntu-latest
    env: 
        GITHUB_PAT: ${{ secrets.CMU_DELPHI_AUTOMATION_MACHINE_DEPENDABOT_PAT }}
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Assign team to PR
        run: gh pr edit "$PR_URL" --add-reviewer "code-reviewers"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}