name: Dependabot auto-assign reviewer
on: pull_request

permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Assign team to PR
        # This is a workaround a limitation in the GitHub CLI.
        # Can probably simplify after this issue is closed:
        # https://github.com/cli/cli/issues/4844
        run: | 
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos${{ github.owner }}/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
            -d '{"team_reviewers":["code-reviewers"]}'
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
